# Generated by Django 5.2.4 on 2025-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_code', models.CharField(max_length=10)),
                ('classification_name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
                ('code_name', models.CharField(max_length=100)),
                ('code_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingUnitCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('code_name', models.CharField(max_length=100)),
                ('code_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('code_name', models.CharField(max_length=100)),
                ('code_description', models.TextField(blank=True)),
            ],
        ),
    ]
