# Generated by Django 5.2.4 on 2025-07-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitsOfMeasure',
            new_name='UnitOfMeasure',
        ),
    ]
