# Generated by Django 5.2.4 on 2025-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_unitsofmeasure_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('sort_order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
    ]
