# Generated by Django 5.2.4 on 2025-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_delete_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemClsCd', models.CharField(max_length=10, unique=True)),
                ('itemClsNm', models.CharField(max_length=100)),
                ('itemClsLvl', models.CharField(max_length=100)),
            ],
        ),
    ]
