# Generated by Django 5.2.4 on 2025-07-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itemsclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsclass',
            name='useYn',
            field=models.BooleanField(default=True),
        ),
    ]
