# Generated by Django 5.2.4 on 2025-08-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itemsclass_useyn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spplr_tpin', models.CharField(max_length=20)),
                ('spplr_nm', models.CharField(max_length=255)),
                ('spplr_bhf_id', models.CharField(max_length=10)),
                ('spplr_invc_no', models.CharField(max_length=50)),
                ('rcpt_ty_cd', models.CharField(max_length=5)),
                ('pmt_ty_cd', models.CharField(max_length=5)),
                ('cfm_dt', models.DateTimeField()),
                ('sales_dt', models.CharField(max_length=8)),
                ('stock_rls_dt', models.DateTimeField(blank=True, null=True)),
                ('tot_item_cnt', models.PositiveIntegerField()),
                ('tot_taxbl_amt', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tot_tax_amt', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tot_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_seq', models.PositiveIntegerField()),
                ('item_cd', models.CharField(max_length=50)),
                ('item_cls_cd', models.CharField(max_length=20)),
                ('item_nm', models.CharField(max_length=255)),
                ('bcd', models.CharField(blank=True, max_length=50, null=True)),
                ('pkg_unit_cd', models.CharField(max_length=10)),
                ('pkg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_unit_cd', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sply_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dc_rt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dc_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_cat_cd', models.CharField(max_length=5)),
                ('ipl_cat_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('tl_cat_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('excise_tx_cat_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('vat_taxbl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_taxbl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ipl_taxbl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tl_taxbl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxbl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ipl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tl_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_tx_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tot_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='main.supplierinvoice')),
            ],
        ),
    ]
