# Generated by Django 5.2.4 on 2025-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_supplierinvoice_supplierinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
