import json

packaging_units = [
    ("AM", "Ampoule", "Ampoule"),
    ("BA", "Barrel", "Barrel"),
    ("BC", "Bottle crate", "Bottle crate"),
    ("BE", "Bundle", "Bundle"),
    ("BF", "Balloon, nonprotected", "Balloon, non-protected"),
    ("BG", "Bag", "Bag"),
    ("BJ", "Bucket", "Bucket"),
    ("BK", "Basket", "Basket"),
    ("BL", "Bale", "Bale"),
    ("BQ", "Bottle, protected cylindrical", "Bottle, protected cylindrical"),
    ("BR", "Bar", "Bar"),
    ("BV", "Bottle, bulbous", "Bottle, bulbous"),
    ("BZ", "Bag", "Bag"),
    ("CA", "Can", "Can"),
    ("CH", "Chest", "Chest"),
    ("CJ", "Coffin", "Coffin"),
    ("CL", "Coil", "Coil"),
    ("CR", "Wooden Box, Wooden Case", "Wooden Box, Wooden Case"),
    ("CS", "Cassette", "Cassette"),
    ("CT", "Carton", "Carton"),
    ("CTN", "Container", "Container"),
    ("CY", "Cylinder", "Cylinder"),
    ("DR", "Drum", "Drum"),
    ("GT", "Extra Countable Item", "Extra Countable Item"),
    ("HH", "Hand Baggage", "Hand Baggage"),
    ("IZ", "Ingots", "Ingots"),
    ("JR", "Jar", "Jar"),
    ("JU", "Jug", "Jug"),
    ("JY", "Jerry CAN Cylindrical", "Jerry CAN Cylindrical"),
    ("KZ", "Canester", "Canester"),
    ("LZ", "Logs, in bundle/bunch/truss", "Logs, in bundle/bunch/truss"),
    ("NT", "Net", "Net"),
    ("OU", "Non-Exterior Packaging Unit", "Non-Exterior Packaging Unit"),
    ("PD", "Poddon", "Poddon"),
    ("PG", "Plate", "Plate"),
    ("PI", "Pipe", "Pipe"),
    ("PO", "Pilot", "Pilot"),
    ("PU", "Traypack", "Traypack"),
    ("RL", "Reel", "Reel"),
    ("RO", "Roll", "Roll"),
    ("RZ", "Rods, in bundle/bunch/truss", "Rods, in bundle/bunch/truss"),
    ("SK", "Skeletoncase", "Skeletoncase"),
    ("TY", "Tank, cylindrical", "Tank, cylindrical"),
    ("VG", "Bulk,gas(at 1031 mbar 15 oC)", "Bulk,gas(at 1031 mbar 15 oC)"),
    ("VL", "Bulk,liquid(at normal temperature/pressure)", "Bulk,liquid(at normal temperature/pressure)"),
    ("VO", "Bulk, solid, large particles(nodules)", "Bulk, solid, large particles(\"nodules\")"),
    ("VQ", "Bulk, gas(liquefied at abnormal temperature/pressure)", "Bulk, gas(liquefied at abnormal temperature/pressure)"),
    ("VR", "Bulk, solid, granular particles(grains)", "Bulk, solid, granular particles(\"grains\")"),
    ("VT", "Extra Bulk Item", "Extra Bulk Item"),
    ("VY", "Bulk, fine particles(powder)", "Bulk, fine particles(\"powder\")"),
    ("ML", "Mills cigarette", "Mills cigarette"),
    ("TN", "TAN", "1TAN REFER TO 20BAGS"),
    ("B/L", "Black Lug", "Refers to a lug or container that is black in color."),
    ("BIN", "Bin", "A container for storing or transporting goods"),
    ("BOTT", "Bottle", "A container typically used for liquids"),
    ("BOUQ", "Bouquet", "A collection of flowers or other items bundled together"),
    ("BOWL", "Bowl", "A round or oval container used for holding food or other items."),
    ("BOX", "Box", "A rectangular container typically used for packaging and storage."),
    ("BUBG", "Budget Bag", "A bag designed for economical or budget-conscious purposes."),
    ("BULK", "Bulk Pack", "Packaging designed for large quantities of items."),
    ("BUNC", "Bunch", "A grouping or collection of items, often tied together."),
    ("BUND", "Bundle", "A group of items bound or packaged together."),
    ("CLEA", "Clear Lid", "A lid or covering that is transparent or see-through."),
    ("EA", "Each", "Indicates individual units or items."),
    ("EACH", "Each", "Similar to \"EA,\" denotes individual units or items."),
    ("ECON", "Economy Bag", "A bag designed for cost-effective or budget-friendly use."),
    ("ECPO", "Econo Poc Sell", "Refers to an economical or budget-friendly pocket for selling items."),
    ("G/L", "Green Lugs", "Lugs or containers that are green in color."),
    ("KARR", "Karripoc", "Specific packaging or container type."),
    ("LABE", "Labels", "Refers to adhesive labels used for marking or identifying items."),
    ("MESH", "Mesh", "Packaging material made of interconnected strands or fibers."),
    ("NETL", "Netlon", "Refers to a type of net or netting used in packaging."),
    ("P/KG", "Per Kilogram", "Indicates pricing or packaging based on weight in kilograms."),
    ("PACK", "PACK", "General term for packaging or packaging units."),
    ("PCRT", "PCRT", "Specific type of packaging or container."),
    ("PILP", "Pilpac", "Specific type of packaging or container."),
    ("POC", "Pocket", "A small container or compartment."),
    ("POCS", "Poc Sell", "Refers to a pocket or small container used for selling items."),
    ("POLY", "Poly Bags", "Bags made of polyethylene or similar materials."),
    ("POT", "Pots", "Containers typically used for planting or holding plants."),
    ("PREP", "Prepack", "Items or units that are prepackaged or prepared."),
    ("PUND", "Pun DTray", "Refers to a tray or container for specific items."),
    ("PUNN", "Punnet - Packaging", "A specific type of packaging often used for fruits or vegetables."),
    ("SLEE", "Sleeve", "A covering or protective layer."),
    ("SOCK", "Sock", "A fabric covering often used for protection or packaging."),
    ("TRAY", "Tray", "A flat, shallow container used for holding or displaying items."),
    ("TRSE", "Tray Sell", "Refers to a tray or container specifically designed for selling items."),
    ("TUB", "TUB", "A container typically with a round shape and open top."),
    ("UNWR", "Unwrap", "Indicates items that are not wrapped or packaged."),
    ("WRAP", "Wraped", "Indicates items that are wrapped or packaged.")
]

fixture = [
    {
        "model": "main.packagingunitcode",
        "pk": idx + 1,
        "fields": {
            "code": code,
            "code_name": code_name,
            "code_description": code_description
        }
    }
    for idx, (code, code_name, code_description) in enumerate(packaging_units)
]

with open("packaging_unit_code.json", "w", encoding="utf-8") as f:
    json.dump(fixture, f, indent=2, ensure_ascii=False)

print("Fixture file 'packaging_unit_code.json' generated successfully!")
