import json

unit_of_measures = [
    ("4B", "Pair", "Pair"),
    ("AV", "Cap", "Cap"),
    ("BA", "Barrel", "Barrel"),
    ("BE", "bundle", "bundle"),
    ("BG", "bag", "bag"),
    ("BL", "block", "block"),
    ("BLL", "BLL Barrel", "BLL Barrel (petroleum) (158,987 dm3)"),
    ("BX", "box", "box"),
    ("CA", "Can", "Can"),
    ("CEL", "Cell", "Cell"),
    ("CMT", "centimetre", "centimetre"),
    ("CR", "CARAT", "CARAT"),
    ("DR", "Drum", "Drum"),
    ("DZ", "Dozen", "Dozen"),
    ("GLL", "Gallon", "Gallon"),
    ("GRM", "Gram", "Gram"),
    ("GRO", "Gross", "Gross"),
    ("KG", "Kilo-Gramme", "Kilo-Gramme"),
    ("KTM", "kilometre", "kilometre"),
    ("KWT", "kilowatt", "kilowatt"),
    ("L", "Litre", "Litre"),
    ("LBR", "pound", "pound"),
    ("LK", "link", "link"),
    ("LTR", "Litre", "Litre"),
    ("M", "Metre", "Metre"),
    ("M2", "Square Metre", "Square Metre"),
    ("M3", "Cubic Metre", "Cubic Metre"),
    ("MGM", "milligram", "milligram"),
    ("MTR", "metre", "metre"),
    ("MWT", "megawatt hour", "megawatt hour (1000 kW.h)"),
    ("NO", "Number", "Number"),
    ("NX", "part per thousand", "part per thousand"),
    ("PA", "packet", "packet"),
    ("PG", "plate", "plate"),
    ("PR", "pair", "pair"),
    ("RL", "reel", "reel"),
    ("RO", "roll", "roll"),
    ("SET", "set", "set"),
    ("ST", "sheet", "sheet"),
    ("TNE", "tonne (metric ton)", "tonne (metric ton)"),
    ("TU", "tube", "tube"),
    ("U", "Pieces/item [Number]", "Pieces/item [Number]"),
    ("YRD", "yard", "yard"),
    ("P1", "Pack", "Pack"),
    ("PL", "Pallet", "Pallet"),
    ("Ft", "Feet", "Feet"),
    ("MM", "Millimetre", "Millimetre"),
    ("In", "Inches", "Inches"),
    ("Oz", "Ounce", "Ounce"),
    ("YR", "Year", "Year"),
    ("MTH", "Month", "Month"),  # changed code from 'M' to 'MTH' to avoid duplicate
    ("Wk", "Week", "Week"),
    ("D", "Day", "Day"),
    ("hr", "Hour", "Hour"),
    ("ha", "Hectare", "Hectare"),
    ("yd2", "Square yards", "Square yards"),
    ("ft2", "Square feet", "Square feet"),
    ("cm2", "Square centimetre", "Square centimetre"),
    ("m2", "Square metre", "Square metre"),
    ("pt", "Pints", "Pints"),
    ("qt", "Quarts", "Quarts"),
    ("mm", "Millilitre", "Millilitre"),
    ("2X", "Meter/Minute", "Meter/Minute"),
    ("4G", "Microliter", "Microliter"),
    ("4O", "Microfarad", "Microfarad"),
    ("4T", "Pikofarad", "Pikofarad"),
    ("A", "Ampere", "Ampere"),
    ("A87", "Gigaohm", "Gigaohm"),
    ("A93", "Gram/Cubic meter", "Gram/Cubic meter"),
    ("ACR", "Acre", "Acre"),
    ("B34", "Kilogram/cubic decimeter", "Kilogram/cubic decimeter"),
    ("B45", "Kilomol", "Kilomol"),
    ("B47", "Kilonewton", "Kilonewton"),
    ("B73", "Meganewton", "Meganewton"),
    ("B75", "Megohm", "Megohm"),
    ("B78", "Megavolt", "Megavolt"),
    ("B84", "Microampere", "Microampere"),
    ("BAG", "Bag", "Bag"),
    ("BAR", "bar", "bar"),
    ("BOT", "Bottle", "Bottle"),
    ("BQK", "Becquerel/kilogram", "Becquerel/kilogram"),
    ("C10", "Millifarad", "Millifarad"),
    ("C36", "Mol per cubic meter", "Mol per cubic meter"),
    ("C38", "Mol per liter", "Mol per liter"),
    ("C39", "Nanoampere", "Nanoampere"),
    ("C3S", "Cubic centimeter/second", "Cubic centimeter/second"),
    ("C41", "Nanofarad", "Nanofarad"),
    ("C56", "Newton/Square millimeter", "Newton/Square millimeter"),
    ("CCM", "Cubic centimeter", "Cubic centimeter"),
    ("CD", "Candela", "Candela"),
    ("CDM", "Cubic decimeter", "Cubic decimeter"),
    ("EA", "Each", "Indicates individual units or items."),
]

fixture = [
    {
        "model": "main.unitofmeasure",
        "pk": idx + 1,
        "fields": {
            "code": code,
            "code_name": code_name,
            "code_description": code_description,
        }
    }
    for idx, (code, code_name, code_description) in enumerate(unit_of_measures)
]

with open("unit_of_measures.json", "w", encoding="utf-8") as f:
    json.dump(fixture, f, indent=2, ensure_ascii=False)

print("Fixture file 'unit_of_measures.json' generated successfully!")
